/* Pure V2 tests. The V1 fixture was generated by the unchanged main core. */
'use strict';
const assert=require('node:assert/strict'), fs=require('node:fs'), M=require('../core.js');
let checks=0;
const check=(value,message)=>{assert.ok(value,message);checks++;};
const same=(a,b,message)=>{assert.deepEqual(a,b,message);checks++;};
const rejects=(f,message)=>{assert.throws(f,undefined,message);checks++;};
const fixture=fs.readFileSync(__dirname+'/fixtures/v1-realistic.json','utf8'), v1=JSON.parse(fixture);
class Storage {
 constructor(data={}){this.data=new Map(Object.entries(data));this.writes=[];}
 getItem(k){return this.data.get(k)??null;}
 setItem(k,v){this.writes.push(k);this.data.set(k,v);}
}
const storage=new Storage({[M.STORAGE.legacy]:fixture});
const loaded=M.load(storage);
check(loaded.migrated,'migrated');same(loaded.state.version,2,'schema');
for(const k of ['points','streak','best','completed','items','stats']) same(loaded.state[k],v1[k],'preserve '+k);
for(const [k,v] of Object.entries(v1.session)) same(loaded.state.session[k],v,'preserve session '+k);
for(const [k,v] of Object.entries(v1.settings)) same(loaded.state.settings[k],v,'preserve setting '+k);
same(storage.getItem(M.STORAGE.backup),fixture,'byte exact backup');same(storage.getItem(M.STORAGE.legacy),fixture,'legacy untouched');
const writes=storage.writes.length;same(M.load(storage).migrated,false,'once only');same(storage.writes.length,writes,'no repeated write');
const quota=new Storage({[M.STORAGE.legacy]:fixture});quota.setItem=()=>{throw Error('quota');};rejects(()=>M.load(quota),'backup failure');same(quota.getItem(M.STORAGE.current),null,'no replacement without backup');
for(const bad of [null,{}, {...v1,version:99},{...v1,points:-1},{...v1,items:[]},{...v1,completed:{14:3}},{...v1,stats:{solved:0}}, {...v1,settings:{range:100}}, {...v1,session:{...v1.session,question:{...v1.session.question,answer:9}}}, JSON.parse('{"version":2,"__proto__":{}}')]) rejects(()=>M.validate(bad),'invalid import');
const corrupt=new Storage({[M.STORAGE.legacy]:'broken'});rejects(()=>M.load(corrupt),'corrupt load');same(corrupt.writes.length,0,'corrupt never overwritten');
const exportFile=M.exportSave(loaded.state,new Date('2026-10-03T10:00:00Z'));same(exportFile.appVersion,'2.0.0','version');same(exportFile.exportedAt,'2026-10-03T10:00:00.000Z','date');
const current=storage.getItem(M.STORAGE.current);same(M.importSave(storage,exportFile,loaded.state),loaded.state,'export import');same(storage.getItem(M.STORAGE.importBackup),current,'import backup');
const importFailure=new Storage({[M.STORAGE.current]:current});importFailure.setItem=()=>{throw Error('quota');};rejects(()=>M.importSave(importFailure,exportFile,loaded.state),'import backup failure');same(importFailure.getItem(M.STORAGE.current),current,'failed import preserves original');
const imported=M.importSave(new Storage(),v1,M.fresh());same(imported.points,v1.points,'v1 import migration');
let seed=413;const random=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296;};
for(const tables of [[1],[10],[4],[7],[4,7,8],M.defaults.tables]) for(const ops of [[true,false],[false,true],[true,true]]) {
 const settings={...M.defaults,area:'tables',tables,mul:ops[0],div:ops[1]}, recent=[];
 for(let n=0;n<100;n++) {
  const q=M.generate(settings,0,{types:{}},recent,random);
  check(tables.includes(q.row),'selected row');check(settings[q.op],'operation');
  same(q.answer,q.op==='mul'?q.a*q.b:q.a/q.b,'arithmetic');
  check(q.b>=1 && q.b<=10,'nonzero divisor');check(Number.isInteger(q.answer),'integer');
  check(q.op==='mul'?q.a>=1 && q.a<=10:q.answer>=1 && q.answer<=10,'small table');
  check(q.key!==recent.at(-1),'no immediate repeats in single table');
  const choices=M.choices(q,100,random);check(new Set(choices).size===3 && choices.includes(q.answer),'choice');
  recent.push(q.key);if(recent.length>12)recent.shift();
 }
}
for(let row=1;row<=10;row++) for(const op of ['mul','div']) {const qs=M.rowQuestions(row,op);same(qs.length,10,'ten rows');same(qs.map(q=>q.answer),Array.from({length:10},(_,i)=>op==='mul'?(i+1)*row:i+1),'ordered answers');}
for(const area of ['arithmetic','tables']) for(const mode of ['off','countdown','stopwatch']) {
 const s=M.fresh(), settings={...s.settings,area,tempo:mode,length:5,tables:[8]};
 s.session=M.startSession(settings,0);let r=s.session;
 const rounds=mode==='countdown'?3:5;
 for(let i=0;i<rounds;i++) {r.question=M.generate(settings,0,s.stats,r.recent,random);M.tick(r,2000);M.answer(s,r.question.answer,2,'2026-10-03');if(s.session) same(M.validate(JSON.parse(JSON.stringify(s))).session,s.session,'session reload');}
 if(mode==='countdown') {check(M.tick(r,120000),'expiry');M.finishRound(s);}
 same(s.session,null,'finished');
 if(area==='arithmetic'&&mode==='off') same(s.completed,{0:3},'normal adventure');else same(s.completed,{},'training no adventure changes');
 const before=s.points;check(M.answer(s,0,0,'2026-10-03').ignored,'duplicate ignored');same(s.points,before,'no double reward');
 if(mode==='stopwatch') {same(Object.keys(s.training.records).length,1,'record');same(s.training.last.elapsed,10000,'elapsed');}
 if(mode==='countdown') same(s.training.last.correct,3,'countdown summary');
 same(M.validate(s),s,'finished save');
}
const a=M.startSession({...M.defaults,tempo:'stopwatch',tables:[4]},0,'training');const b=M.startSession({...M.defaults,tempo:'stopwatch',tables:[8]},0,'training');check(a.profile!==b.profile,'incompatible rows');b.learning.mode='choice';check(a.profile!==M.profileKey(b),'incompatible answer mode');
const rows=M.startSession({...M.defaults,area:'tables',tempo:'countdown'},0,'training','rows',8,'div');same(rows.timer.mode,'off','no row countdown');
const s=M.fresh();s.settings={...s.settings,area:'tables',tempo:'stopwatch',tables:[8]};s.session=M.startSession(s.settings,0,'training','rows',8,'div');
for(let i=0;i<10;i++) {const r=s.session;r.question=M.rowQuestions(8,'div')[i];M.tick(r,1000);same(M.validate(s),s,'rows reload');if(i===2)M.answer(s,99,1,'2026-10-03');M.answer(s,r.question.answer,1,'2026-10-03');}
same(Object.keys(s.training.records).length,0,'errors exclude records');same(s.training.last.correct,10,'ten rows done');same(s.completed,{},'no level mutation');
console.log(`PASS: ${checks} V2 checks: real V1 migration, exact backups, validation, imports, all tables, integer division, rows, timers, rewards, reload and compatible records.`);
